version: 0.1
env:
  secrets-manager:
    TOKEN: SonarCloud3:tokenForSonar
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=java-reachability-playground -Dsonar.organization=java-reachability-playground -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN 