version: 0.1
env:
  Secrets-Manager:
    TOKEN: SonarCloud2:tokenForSonar
variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    MAVEN_HOME: "/usr/share/maven"
    MAVEN_CONFIG: ".m2"
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=Goat-Security -Dsonar.organization=Goat-Security -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$dca5e6854f2738a744a046eaff49b47e4ef3d1be