version: 0.1
env:
  secrets-manager:
    TOKEN: NewSonarCloudKey:tokenForSonar
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=Goat-Security -Dsonar.organization=Goat-Security -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$NewSonarCloudKey